name: getx_wanandroid
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: 1.1.6
  get: 3.24.0
  flutter_screenutil: ^4.0.2+5  
  cupertino_icons: ^1.0.0
  flutter_easyrefresh: ^2.1.8
  flare_flutter: ^2.0.6
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
  assets:
    - assets/flare/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
